; PlatformIO Project Configuration File for Arduino Framework
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = partitions.csv

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/beegee-tokyo/DHTesp.git#1.19
    https://github.com/tzapu/WiFiManager.git
    adafruit/Adafruit SGP30 Sensor @ ^1.2.3

build_flags =
    -D ARDUINO_ESP32_DEV
    -I include
    -I src

# Pre-script to prepare files for SPIFFS if necessary
extra_scripts = pre:tools/mkspiffs.py

[platformio]
default_envs = esp32dev
